# Project-wide Gradle settings
org.gradle.java.home=D:/Program/Java/jdk-17

# Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# NDK version (must match installed NDK)
ndkVersion=27.2.12479018

# CMake version (must match installed CMake)
cmakeVersion=3.22.1

# Target SDK versions
compileSdk=36
minSdk=29
targetSdk=36

# Version
versionCode=1
versionName=1.0.0-alpha01
