package com.learnthis.common

enum class AppLanguage(val tag: String, val displayName: String, val translationSupported: Boolean = true) {
 TAMIL("ta", "Tamil"),
 HINDI("hi", "Hindi"),
 ENGLISH("en", "English"),
 TELUGU("te", "Telugu"),
 MALAYALAM("ml", "Malayalam", translationSupported = false),
 KANNADA("kn", "Kannada"),
 BENGALI("bn", "Bengali"),
 MARATHI("mr", "Marathi"),
 GUJARATI("gu", "Gujarati"),
 URDU("ur", "Urdu"),
 ARABIC("ar", "Arabic"),
 CHINESE("zh", "Chinese"),
 FRENCH("fr", "French"),
 GERMAN("de", "German"),
 SPANISH("es", "Spanish"),
 PORTUGUESE("pt", "Portuguese"),
 ITALIAN("it", "Italian"),
 JAPANESE("ja", "Japanese"),
 KOREAN("ko", "Korean"),
 RUSSIAN("ru", "Russian"),
 UKRAINIAN("uk", "Ukrainian"),
 TURKISH("tr", "Turkish"),
 THAI("th", "Thai"),
 VIETNAMESE("vi", "Vietnamese"),
 INDONESIAN("id", "Indonesian"),
 MALAY("ms", "Malay"),
 DUTCH("nl", "Dutch"),
 POLISH("pl", "Polish"),
 ROMANIAN("ro", "Romanian"),
 GREEK("el", "Greek"),
 HEBREW("he", "Hebrew"),
 PERSIAN("fa", "Persian"),
 SWAHILI("sw", "Swahili"),
 AFRIKAANS("af", "Afrikaans"),
 ALBANIAN("sq", "Albanian"),
 BELARUSIAN("be", "Belarusian"),
 BULGARIAN("bg", "Bulgarian"),
 CATALAN("ca", "Catalan"),
 CROATIAN("hr", "Croatian"),
 CZECH("cs", "Czech"),
 DANISH("da", "Danish"),
 ESTONIAN("et", "Estonian"),
 FINNISH("fi", "Finnish"),
 GALICIAN("gl", "Galician"),
 GEORGIAN("ka", "Georgian"),
 HUNGARIAN("hu", "Hungarian"),
 ICELANDIC("is", "Icelandic"),
 IRISH("ga", "Irish"),
 LATVIAN("lv", "Latvian"),
 LITHUANIAN("lt", "Lithuanian"),
 MACEDONIAN("mk", "Macedonian"),
 MALTESE("mt", "Maltese"),
 NORWEGIAN("no", "Norwegian"),
 SLOVAK("sk", "Slovak"),
 SLOVENIAN("sl", "Slovenian"),
 SWEDISH("sv", "Swedish"),
 WELSH("cy", "Welsh");

 companion object {
 fun fromTag(tag: String?) = entries.firstOrNull { it.tag == tag }
 val onboardingLanguages = listOf(TAMIL, HINDI, ENGLISH, TELUGU, MALAYALAM, KANNADA, BENGALI, MARATHI)
 .filter { it.translationSupported }
 }
}
